---
- name: setup_server
  hosts: default
  become: true
  vars:
    packages: ["lsscsi", "mingw-w64", "veil"]
  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: install packages
      apt: name='{{ packages }}' state=latest

    - name: setup veil
      shell: /usr/share/veil/config/setup.sh --force --silent
