---
- name: server
  hosts: default
  become: true
  vars:
    packages: ["lsscsi"]
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: Install Package
      apt: name='{{ packages }}' state=latest
